### Problem 1

Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

In [1]:
import numpy as np

In [2]:
def gen_vander_matrix(input_vector, col, increasing = False):
    
    if not increasing:
        
        output_matrix = np.array([x**(col-1-i) for x in input_vector for i in range(col)]).reshape(input_vector.size,col)
        
    elif increasing:
        
        output_matrix = np.array([x**i for x in input_vector for i in range(col)]).reshape(input_vector.size,col)
    
    return output_matrix


In [8]:
inputvector = np.array([1,2,3,4,5])

col_output_matrix = 3

In [13]:
matrix_decreasing_order = gen_vander_matrix(inputvector, col_output_matrix, False)

matrix_decreasing_order

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [14]:
matrix_increasing_order = gen_vander_matrix(inputvector, col_output_matrix, True)

matrix_increasing_order

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])

### Problem 2
Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
import numpy as np
import pandas as pd

In [9]:
# 1st method

def moving_average_calcualte(iterable, window_size):
    
    ''' 
    moving_average_calcualte function will take two arguments, first is in an iterable and 
    second is the window_size and 
    return the cummalative sum on that window_size
    
    '''
    
    # converting the iterable into a pandas series
    
    data_series = pd.Series(iterable)
    
    # returning the cummalative sum on that window_size and removing the 'NaN' values
    
#     return data_series.rolling(window_size).mean().iloc[n-1:].values
    print(data_series.rolling(window_size).mean().iloc[window_size - 1 : ].values)
    
    

In [10]:
my_array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [11]:
window = 3

In [12]:
moving_average_calcualte(my_array, window)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]


In [1]:
import numpy as np

In [11]:
# 2nd method

def moving_average_calcualte(iterable, window_size):
    
    temp = np.cumsum(iterable, dtype = float)
    
    temp[window_size : ] = temp[window_size : ] - temp[ : -window_size]
    
    return (temp[window_size - 1 : ] / window_size)


In [13]:
my_array = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])

In [14]:
window = 3

In [15]:
moving_average_calcualte(my_array, window)

array([  5.        ,   4.66666667,   5.66666667,   6.66666667,
         9.66666667,  28.66666667,  49.33333333,  72.66666667,
        84.        ,  93.33333333, 116.33333333])

### Assignment END